### PR TITLE
UX draft for patient views

### PR DESCRIPTION
**Pull request by Karl-Heinrich**
**Just a suggestion.**

We don't have to implement this!

Just gives us something to show to people interested in our project and might be of some use
when we create our pitch video.

It's an ugly draft, the implementation should of course be much cleaner.

### CODE REVIEW

**Comment by schaeferto** [comment]
Find ich gut. Dann haben wir zumindest etwas, was sich bewegt ;-)

**Comment by yogan** [comment]
What shall we do with this? I don't have any opinion here. The GIF does not reflect how the app currently looks, but it also clearly states that it's just an UX prototype. And having something fancy on the GitHub front page of the project is indeed nice.

**Comment by Karl-Heinrich** [comment]
It helps people envision what a finished product **could** look like.

It might also attract new contributors. Nobody expects a finished product from a hackathon, rather a very well thought out concept or idea.

We already have a much cleaner version of this concept (see below). We could keep both to show the progress we made or just add the later (blue) one. Let me know!

drcovidweg

**Comment by yogan** [comment]
This looks even cooler! I like it. But still I don't want to make the decision, maybe a few others want to say a word?

**Comment by t-animal** [comment]
We discussed this and came to the conclusion that we cannot easily implement it as it hugely depends on domain knowledge we don't have.

**Comment by yogan** [comment]
I see your point on wanting to emphasize that the project can be used for different scenarios. However, the medical practice is a catchy use case. And we have used that example all over the place, e.g. in the [devpost project description](https://devpost.com/software/digitales-warten) or the [YouTube video](https://www.youtube.com/watch?v=SX5l_fIEzcs), so I think this thematically fits very well.

Presenting a specific use case makes it easier for people to grasp the project. We can add a clear statement like "the project is not specific to medical practices, but can be used at any place where a limited amount of customers shall be served without forcing them to wait at the venue".

So the question is more: do we want to show those prototype UX animations, even if they don't match the current project look and feel, and only show a specific use-case (thought probably the most important one).

**Comment by Karl-Heinrich** [comment]
We can also adapt the UX prototype to what ever we want. If you prefer a supermarket themed concept, just say the word.

As with any PR, everything is up to discussion.

**Comment by Gronner** [comment]
I would close this as stale, if this become interesting again, we can always reopen the pull request

**Pull request closed without merging**
